### ISSUE TITLE
Media importer is not profile aware

### ISSUE THREAD

**Issue by enen92** [Montellese/xbmc#59]
Media importer seems not to take into account Kodi profiles. I know profiles need a huge rework in Kodi but, either way, decided to post.

Steps to reproduce:

1 - Master profile is configured with a media import (Movies) from plex
2 - Create a secondary profile and choose not to import anything from master profile
3 - Login into to secondary profile
4 - Master profile shows empty as expected (no movies, no shows, no addons, etc)
5 - Navigate to Settings -> Media Import -> Active Media Providers
6 - Plex provider is shown in active media providers. Plex mediaimporter addon is not even installed for this user:

![Screenshot 2020-01-05 at 14 51 11](https://user-images.githubusercontent.com/7375276/71781817-e92a8a80-2fca-11ea-8531-f75263a9ea8b.png)

**Comment by Montellese** [comment]
TBH I haven't looked at profiles yet. I also don't really know how they work right now. I always expected them to use separate database files in which case media providers and imports would not be shared. But if they use the same database I'll have to take a look.

**Comment by Montellese** [comment]
I finally had time to look into this and I think I figured out what the problem is. I'll provide a test build ASAP.

**Comment by Montellese** [comment]
Thanks for the detailed feedback. 

I know the error you're talking about but I don't know if I can fix it in the add-on. There already is a try-except block for `socket.timeout` around that part but for some reason it isn't properly handled. It seems to be an issue with Kodi's Python integration. IIRC @sualfred knows more about it.

**Comment by sualfred** [comment]
I havent had this annoying Python Exceptiom handling bug anymore since a while. @yol wanted to take a look at it and afaik he never was able to reproduce. 

Dunno what has been changed that I dont get it anymore.

**Comment by Montellese** [comment]
I haven't seen the issue for a while either but recently I've ran into it quite a few times. But also remember that media import is currently based on a patched Matrix 19.0 so maybe there have been improvements in v20 which haven't made their way into media import yet.

**Comment by sualfred** [comment]
@Montellese 
I only have your fork installed in my dev device (Performance #2). Can't say anything about v20.
