### ISSUE TITLE
Go through the whole import process of one media type before processing the next

### ISSUE THREAD

**Issue by Montellese** [Montellese/xbmc#61]
Right now when synchronizing / importing a complete media provider Kodi first retrieves all items for all media types, then synchronizes all items for all media types and then cleans up all items for all media types. If anything goes wrong at any point in the process the whole process will be aborted.

Therefore it would be better to retrieve, synchronize and cleanup all items for the first media type and then for the second and so on.

**Comment by Long-Man** [comment]
Maybe do it by libraries. That way complete libraries would be available even if it has to be aborted before all libraries are completed.

**Comment by Montellese** [comment]
Unfortunately Kodi doesn't know the concept of "libraries" like Emby or Plex does. Therefore Kodi cannot tell if all items of an Emby / Plex library have been imported or not.

**Comment by Long-Man** [comment]
I was thinking of what happens when only one or two libraries are selected. Only media items from those libraries are pulled. Are these not processed independently while importing?

**Comment by Montellese** [comment]
Being able to select the libraries to import is a feature specific to mediaimporter.emby. While mediaimporter.plex hasa similar feature it works differently there. Therefore Kodi has no idea that there are different Emby libraries. Kodi simply tells the add-on to import all movies and the add-on does that (while respecting the selected libraries). Then Kodi asks for all tvshows and so on...

**Comment by Long-Man** [comment]
Ok. That makes sense.

**Comment by Long-Man** [comment]
Could the logic be placed in the addons since they know what the server has to offer. Could the Emby importer feed Kodi one library at a time?

**Comment by Montellese** [comment]
That doesn't work because the add-on passes all imported items to Kodi and Kodi then determines which items are new, updated or have been removed. If we pass one library at a time and Kodi has no notion of "libraries" it will consider all missing items (from other libraries) as removed.

**Comment by Montellese** [comment]
I have changed the import logic in Kodi to completely process one set of media items before importing the next. That way it e.g. first syncs all movies, then all music videos and then all tv shows. If one of them fails or takes long the others will already have finished without being blocked.
