### ISSUE TITLE
[Skin/estuary] Missing icon for 'Media sources'

### ISSUE THREAD

**Issue by flubshi** [Montellese/xbmc#66]
A minor, but noticed in milhouse build and when compiled from source: It looks like the icon for `Media sources` in settings is missing:

![image](https://user-images.githubusercontent.com/4031504/78812073-2556f800-79cb-11ea-8b79-d3e8f1951538.png)

Seems like just file `icons/settings/mediasources.png` is missing, definition is there:
```xml
<item>
	<label>$LOCALIZE[753]</label>
	<onclick>ActivateWindow(MediaSourceBrowser)</onclick>
	<icon>icons/settings/mediasources.png</icon>
</item>
```

**Comment by Montellese** [comment]
This is platform independent. I'm no designer so I simply didn't come up with any icon. I also expect that the whole node will be moved into "Media" (Medien) instead. For now it's right there in the overview so that it's easier to find.
