### ISSUE TITLE
Context menu "reset resume position" does not update the item on Emby

### ISSUE THREAD

**Issue by sualfred** [Montellese/xbmc#69]
Resetting the resume position (context menu option introduced in Kodi Leia) for in progress items does not reset reset the progress on the server.

To reproduce:
-> Start a episode, jump to the middle, stop the playback
-> Open the context menu on the item and select "reset item position"
-> Kodi progress is set to `0` but not on the server

**Comment by Montellese** [comment]
Should be fixed with bcaf5f29969add7490e8635fb11468aa2e5f076a.
