### ISSUE TITLE
Problem Installing the Kodi Netflix add-on:

### ISSUE THREAD

**Issue by 27hectormanuel** [Montellese/xbmc#71]
Hi, I had problems installing kodi's Netflix add-on. 

I keep getting this problem, "**The dependency on xbmc.python version 2.26.0 could not be satisfied**"
[repository.castagnait-1.0.0.zip](https://github.com/Montellese/xbmc/files/4535608/repository.castagnait-1.0.0.zip)
@Montellese @CastagnaIT

Is it the preview version that you are using is not compatible?

**Comment by Montellese** [comment]
Kodi Matrix alphas require all python-based add-ons to support Python 3 instead of Python 2.7. They have to set the version of `xbmc.python` to `3.0.0`.
