### ISSUE TITLE
Some items are still left in the DB after deletion on the server

### ISSUE THREAD

**Issue by sualfred** [Montellese/xbmc#78]
As reported on Slack Kodi isn't removing all removed items on the startup fast sync.

The log is reporting the correct amount of removed data, but it's not removing all of them:
https://paste.kodi.tv/ovaporireh.kodi

Tested it twice and can reproduce it:
- Close Kodi
- Delete a couple of shows on Emby
- Start Kodi and let the fast sync kick in

As discussed a temporary advanced logging is required on my end to see why this is happening.

**Comment by Montellese** [comment]
Should be fixed with my rework of the video import handlers which has been released with the Matrix RC1 test builds.
