### ISSUE TITLE
MediaImport Setting Description and Explanation swapped.

### ISSUE THREAD

**Issue by Long-Man** [Montellese/xbmc#79]
Settings>Services>UPnP/DLNA 
Section: Media Import
**Current**
Description - Note that addo-ons installed from zip .....
Explanation - Import media items from UPnP Servers

**Expected**
description - Import media items from UPnP Servers
Explanation - Note that addo-ons installed from zip .....

The explanation seems more like a prompt than an explanation

**Comment by Montellese** [comment]
Thanks for the report. This is due to a merge conflict I messed up during the rebase onto RC1. I fixed it in the branch. The explanation is a different string that didn't show up anywhere.

**Comment by Long-Man** [comment]
Can confirm the fix.
